model_path: null
image_dir: '../../data/raw/'
logs_dir: '../../reports/mlruns/'
batch_size: 64
num_classes: 3
num_epochs: 10
num_workers: 8 # edit for your CPU
val_proportion: 0.15
test_proportion: 0.15